Repository GameLabGraz/Maroon, pull requests merged in 2021-02, with the labels that each got.

#302 Remove quicksearch
  unity/Assets/0Refactored/reusablePrefabs/questManager.meta
  unity/Packages/manifest.json
  unity/Packages/packages-lock.json
  unity/ProjectSettings/PackageManagerSettings.asset
Labels: maintenance

#305 291 load network manager
  unity/Assets/0Refactored/GlobalEntities/BootstrappingManager/BootstrappingManager.cs
  unity/Assets/0Refactored/GlobalEntities/GlobalEntityLoader/GlobalEntities.prefab
  unity/Assets/0Refactored/GlobalEntities/GlobalEntityLoader/GlobalEntityLoader.cs
  unity/Assets/0Refactored/GlobalEntities/Network/scripts/ExperimentSync/ExperimentNetworkSync.cs
  unity/Assets/0Refactored/GlobalEntities/Network/scripts/ListServer.cs
  unity/Assets/0Refactored/GlobalEntities/Network/scripts/MaroonNetworkDiscovery.cs
  unity/Assets/0Refactored/GlobalEntities/Network/scripts/MaroonNetworkManager.cs
  unity/Assets/0Refactored/GlobalEntities/Network/scripts/NetworkControl.cs
  unity/Assets/0Refactored/GlobalEntities/Network/scripts/NetworkInfoPanel.cs
  unity/Assets/0Refactored/GlobalEntities/Network/scripts/NetworkManager.cs
  unity/Assets/0Refactored/GlobalEntities/Network/scripts/NetworkManager.cs.meta
  unity/Assets/0Refactored/GlobalEntities/Network/scripts/NetworkPlayer.cs
  unity/Assets/0Refactored/GlobalEntities/Network/scripts/NetworkStatusStation.cs
  unity/Assets/0Refactored/GlobalEntities/Network/scripts/PasswordUI.cs
  unity/Assets/0Refactored/GlobalEntities/Network/scripts/PortForwarding.cs
  unity/Assets/0Refactored/GlobalEntities/Network/scripts/SceneChangeCountdown.cs
  unity/Assets/0Refactored/GlobalEntities/SceneManager/Scripts/SceneManager.cs
  unity/Assets/0Refactored/reusableGui/Menu/PrefabsBase/scrMenuButtonServer.cs
  unity/Assets/0Refactored/reusableGui/Menu/PrefabsColumns/scrMenuColumnLaboratorySelectionDetail.cs
  unity/Assets/0Refactored/reusableGui/Menu/PrefabsColumns/scrMenuColumnNetwork.cs
  unity/Assets/0Refactored/reusableGui/Menu/PrefabsColumns/scrMenuColumnNetworkKick.cs
  unity/Assets/0Refactored/reusableGui/Menu/PrefabsColumns/scrMenuColumnPauseMenu.cs
  unity/Assets/0Refactored/reusableScripts/PlatformControls/BaseControls/EnterScene.cs
  unity/Assets/0Refactored/scenes/experiments/FaradaysLaw/Scripts/FaradysLawNetworkSync.cs
  unity/Assets/0Refactored/scenes/experiments/HuygensPrinciple/scripts/HuygensNetworkSync.cs
  unity/Assets/0Refactored/scenes/experiments/Pendulum/Scripts/PendulumNetworkSync.cs
  unity/Assets/0Refactored/scenes/experiments/SortingAlgorithms/scripts/QuizScore.cs
  unity/Assets/0Refactored/scenes/experiments/SortingAlgorithms/scripts/SortingController.cs
  unity/Assets/0Refactored/scenes/experiments/SortingAlgorithms/scripts/SortingNetworkSync.cs
  unity/Assets/0Refactored/scenes/experiments/VanDeGraaffGenerator/Scripts/VanDeGraaffNetworkSync.cs
  unity/Assets/0Refactored/scenes/experiments/Whiteboard/Scripts/WhiteboardNetworkSync.cs
  unity/Assets/0Refactored/scenes/laboratory/Laboratory.pc.unity
  unity/Assets/0Refactored/scenes/laboratory/Scripts/ExitToMainMenuPC.cs
  unity/Assets/0Refactored/scenes/laboratory/prefabs/InfoSign/Scripts/scrInfoSignEnterScene.cs
  unity/Assets/0Refactored/scenes/special/MainMenu.pc.unity
  unity/Assets/0Unused/oldMenu.meta
  unity/Assets/Scripts/Assessment/BrowserInterface.jslib.meta
Labels: enhancement

#304 186 audio manager
  unity/Assets/0Refactored/GlobalEntities/soundManager/SoundManager.cs
  unity/Assets/0Refactored/reusableGui/Menu/PrefabsColumns/preMenuColumnAudio.prefab
  unity/Assets/0Refactored/reusableGui/Menu/PrefabsColumns/scrMenuColumnAudio.cs
Labels: feature

#310 Feature/maroon 301 sorting issues
  unity/Assets/Maroon/reusableFonts/LiberationSansSDFOverlay.asset
  unity/Assets/Maroon/reusableFonts/LiberationSansSDFOverlay.asset.meta
  unity/Assets/Maroon/reusableFonts/calling-code.meta
  unity/Assets/Maroon/reusableFonts/calling-code/CallingCode-Regular SDF.asset
  unity/Assets/Maroon/reusableFonts/calling-code/CallingCode-Regular SDF.asset.meta
  unity/Assets/Maroon/reusableFonts/calling-code/CallingCode-Regular.otf
  unity/Assets/Maroon/reusableFonts/calling-code/CallingCode-Regular.otf.meta
  unity/Assets/Maroon/reusableFonts/calling-code/CallingCode-Regular.ttf
  unity/Assets/Maroon/reusableFonts/calling-code/CallingCode-Regular.ttf.meta
  unity/Assets/Maroon/reusableFonts/calling-code/License.txt
  unity/Assets/Maroon/reusableFonts/calling-code/License.txt.meta
  unity/Assets/Maroon/reusableGui/NewUI/Resources/Dropdown.prefab
  unity/Assets/Maroon/scenes/experiments/SortingAlgorithms/Images.meta
  unity/Assets/Maroon/scenes/experiments/SortingAlgorithms/Images/SortingSprite.png
  unity/Assets/Maroon/scenes/experiments/SortingAlgorithms/Images/SortingSprite.png.meta
  unity/Assets/Maroon/scenes/experiments/SortingAlgorithms/fonts.meta
  unity/Assets/Maroon/scenes/experiments/SortingAlgorithms/prefabs/ArrayPlace.prefab
  unity/Assets/Maroon/scenes/experiments/SortingAlgorithms/prefabs/Bucket.prefab
  unity/Assets/Maroon/scenes/experiments/SortingAlgorithms/prefabs/SortingAlg.prefab
  unity/Assets/Materials.meta
  unity/Assets/Materials/Dissolve.meta
  unity/Assets/Materials/Dissolve/DissolveHandler.cs
  unity/Assets/Materials/Dissolve/DissolveHandler.cs.meta
  unity/Assets/Materials/Dissolve/DissolvePattern.png
  unity/Assets/Materials/Dissolve/DissolvePattern.png.meta
  unity/Assets/Materials/Dissolve/DissolveShader.shader
  unity/Assets/Materials/Dissolve/DissolveShader.shader.meta
  unity/Assets/Materials/Dissolve/DissolvingRed.mat
  unity/Assets/Materials/Dissolve/DissolvingRed.mat.meta
  unity/Assets/Materials/SpotLight.mat
  unity/Assets/Materials/SpotLight.mat.meta
  unity/Assets/Models.meta
  unity/Assets/Models/SortingAlgorithms.meta
  unity/Assets/Models/SortingAlgorithms/BaseMaterial.mat
  unity/Assets/Models/SortingAlgorithms/BaseMaterial.mat.meta
  unity/Assets/Models/SortingAlgorithms/DisplayMaterial.mat
  unity/Assets/Models/SortingAlgorithms/DisplayMaterial.mat.meta
  unity/Assets/Models/SortingAlgorithms/sortingMachine.fbx
  unity/Assets/Models/SortingAlgorithms/sortingMachine.fbx.meta
  unity/Assets/Resources/MLG/sorting.xml
Labels: defect
