Repository GameLabGraz/Maroon, pull requests merged in 2022-12, with the labels that each got.

#425 Update .gitignore with recommended entries
  .gitignore
Labels: maintenance

#430 defect/Maroon-429-DuplicateLanguageKeys: removed duplicate keys from experiment MLG files
  unity/Assets/Resources/MLG/titration.xml
  unity/Assets/Resources/MLG/wavepoint_experiment.xml
Labels: defect

#431 defect/Maroon-387-AudioBarIsntSetToFullAtTheBeginning: fixed audio settings menu
  unity/Assets/Maroon/GlobalEntities/SoundManager/SoundManager.cs
  unity/Assets/Maroon/SharedEntities/Player/ModeFirstPerson/ModeFirstPerson.cs
  unity/Assets/Maroon/SharedEntities/Player/ModeFirstPerson/ModeFirstPerson.prefab
  unity/Assets/Maroon/reusableGui/Menu/PrefabsColumns/scrMenuColumnAudio.cs
Labels: defect

#432 Feature/maroon 323 test automation
  unity/Assets/Tests.meta
  unity/Assets/Tests/EditModeTests.meta
  unity/Assets/Tests/EditModeTests/ContentValidation.meta
  unity/Assets/Tests/EditModeTests/ContentValidation/PcSceneValidationTests.cs
  unity/Assets/Tests/EditModeTests/ContentValidation/PcSceneValidationTests.cs.meta
  unity/Assets/Tests/EditModeTests/ContentValidation/RunSceneValidationTestsDuringBuild.cs
  unity/Assets/Tests/EditModeTests/ContentValidation/RunSceneValidationTestsDuringBuild.cs.meta
  unity/Assets/Tests/EditModeTests/ContentValidation/RunSceneValidationTestsFromContextMenu.cs
  unity/Assets/Tests/EditModeTests/ContentValidation/RunSceneValidationTestsFromContextMenu.cs.meta
  unity/Assets/Tests/EditModeTests/ContentValidation/SceneValidationBaseFixture.cs
  unity/Assets/Tests/EditModeTests/ContentValidation/SceneValidationBaseFixture.cs.meta
  unity/Assets/Tests/EditModeTests/ContentValidation/ScenesProvider.cs
  unity/Assets/Tests/EditModeTests/ContentValidation/ScenesProvider.cs.meta
  unity/Assets/Tests/EditModeTests/ContentValidation/VrSceneValdiationTests.cs
  unity/Assets/Tests/EditModeTests/ContentValidation/VrSceneValdiationTests.cs.meta
  unity/Assets/Tests/EditModeTests/EditModeTests.asmdef
  unity/Assets/Tests/EditModeTests/EditModeTests.asmdef.meta
  unity/Assets/Tests/PlayModeTests.meta
  unity/Assets/Tests/PlayModeTests/PcMenuTests.meta
  unity/Assets/Tests/PlayModeTests/PcMenuTests/AudioMenuTests.cs
  unity/Assets/Tests/PlayModeTests/PcMenuTests/AudioMenuTests.cs.meta
  unity/Assets/Tests/PlayModeTests/PcMenuTests/MainMenuLanguageTests.cs
  unity/Assets/Tests/PlayModeTests/PcMenuTests/MainMenuLanguageTests.cs.meta
  unity/Assets/Tests/PlayModeTests/PcMenuTests/MainMenuTests.cs
  unity/Assets/Tests/PlayModeTests/PcMenuTests/MainMenuTests.cs.meta
  unity/Assets/Tests/PlayModeTests/PcMenuTests/MenuLanguageTestBaseFixture.cs
  unity/Assets/Tests/PlayModeTests/PcMenuTests/MenuLanguageTestBaseFixture.cs.meta
  unity/Assets/Tests/PlayModeTests/PcMenuTests/PauseMenuLanguageTests.cs
  unity/Assets/Tests/PlayModeTests/PcMenuTests/PauseMenuLanguageTests.cs.meta
  unity/Assets/Tests/PlayModeTests/PlayModeTests.asmdef
  unity/Assets/Tests/PlayModeTests/PlayModeTests.asmdef.meta
  unity/Assets/Tests/PlayModeTests/ProofOfConcept.meta
  unity/Assets/Tests/PlayModeTests/ProofOfConcept/FallingCoilTests.cs
  unity/Assets/Tests/PlayModeTests/ProofOfConcept/FallingCoilTests.cs.meta
  unity/Assets/Tests/Utilities.meta
  unity/Assets/Tests/Utilities/Constants.cs
  unity/Assets/Tests/Utilities/Constants.cs.meta
  unity/Assets/Tests/Utilities/CustomAttributes.cs
  unity/Assets/Tests/Utilities/CustomAttributes.cs.meta
  unity/Assets/Tests/Utilities/PlaymodeUtilities.cs
  unity/Assets/Tests/Utilities/PlaymodeUtilities.cs.meta
  unity/Assets/Tests/Utilities/TestUtilities.asmdef
  unity/Assets/Tests/Utilities/TestUtilities.asmdef.meta
  unity/Assets/Tests/Utilities/UtilityFunctions.cs
  unity/Assets/Tests/Utilities/UtilityFunctions.cs.meta
Labels: bsc-/msc-thesis
